---

- name: stop application
  command: pm2 delete all
  become: yes
  ignore_errors: yes
      
- name: start application
  command: pm2 start {{ app_path }}/{{ server_file}}
  ignore_errors: yes
  become: yes

- name: restart application
  service: name=pm2-init.sh state=restarted
  when: pm2_service_state != 'stopped'
  
- name: restart nginx
  service: name=nginx state=restarted
