---
- name: MongoDB | Fetch GPG key
  sudo: yes
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  tags: mongodb

- name: MongoDB | Add 10 gen repository
  sudo: yes
  shell:
    echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list creates=/etc/apt/sources.list.d/10gen.list

- name: MongoDB | Install latest mongodb
  sudo: yes
  apt: pkg=mongodb-10gen update-cache=yes
  tags: mongodb

- name: MongoDB | Run mongo daemon
  sudo: yes
  service: name=mongodb state=started
  tags: mongodb
  

# https://github.com/brianium/vagrant-ansible-mean/blob/master/provisioning/roles/mongodb/tasks/main.yml

# http://cloudmesh.github.io/introduction_to_cloud_computing/class/lesson/ansible_playbook.html

# mongo cluster - https://github.com/ansible/ansible-examples/tree/master/mongodb
