---

- name: Ensure that the application file permissions are set properly
  file: path={{ env_path }}
        recurse=yes
        owner={{ nodeapp_user }}
        group={{ nodeapp_group }}
        state=directory
  notify: restart application

- name: Create a symlink for legacy node issue
  command: ln -s /usr/bin/nodejs /usr/bin/node  
